name: docker_dart
description: A sample web application
dependencies:
  core_elements: any
  mongo_dart: any
  paper_elements: any
  polymer: any
  redstone: any
  shelf: any
  shelf_static: any
transformers:
- polymer:
    entry_points: web/index.html
