name: docker_dart
description: A sample web application
dependencies:
  polymer: any
  core_elements: any
  paper_elements: any  
  shelf: any
  shelf_static: any
transformers:
- polymer:
    entry_points: web/index.html